import Anthropic from '@anthropic-ai/sdk';
import { writeFileSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import type { RoomMessage, SceneConfig } from '../types.js';

/**
 * Narrator — post-processes a raw scenario transcript into a narrative story.
 *
 * Takes the RoomMessage[] captured by ScenarioRunner, formats them as a
 * readable transcript, and calls Haiku to rewrite it as prose.
 */
export class Narrator {
  private client: Anthropic;

  constructor() {
    this.client = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
    });
  }

  formatTranscript(messages: RoomMessage[]): string {
    return messages
      .filter((msg) => msg.type !== 'system')
      .map((msg) => {
        if (msg.type === 'scene') return `[SCENE] ${msg.content}`;
        if (msg.type === 'emote') return `*${msg.from} ${msg.content}*`;
        return `${msg.from}: ${msg.content}`;
      })
      .join('\n');
  }

  async generateNarrative(
    messages: RoomMessage[],
    sceneConfig: SceneConfig | null,
    outputPath: string,
  ): Promise<string> {
    const transcript = this.formatTranscript(messages);
    const sceneName = sceneConfig?.name ?? 'Unknown Scene';
    const sceneDescription = sceneConfig?.description ?? '';

    console.log('\nGenerating narrative from transcript...');

    const prompt = [
      `You are a skilled author writing science fiction crossover short stories.`,
      ``,
      `Scene: "${sceneName}"`,
      ``,
      `Context:`,
      sceneDescription,
      ``,
      `Raw transcript:`,
      `---`,
      transcript,
      `---`,
      ``,
      `Rewrite this transcript as a polished narrative short story. Transform the raw dialogue`,
      `and stage directions into flowing prose. Preserve character voices and key plot beats.`,
      `Add atmospheric description between exchanges where it helps pacing. Keep the same`,
      `sequence of events. Aim for 600-1000 words.`,
    ].join('\n');

    const response = await this.client.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 2000,
      messages: [{ role: 'user', content: prompt }],
    });

    const textBlock = response.content.find((b): b is Anthropic.TextBlock => b.type === 'text');
    const narrative = textBlock ? textBlock.text : transcript;

    // Write output
    mkdirSync(dirname(outputPath), { recursive: true });
    const output = [
      `# ${sceneName}`,
      ``,
      `*Generated by fsm-agents scenario runner*`,
      ``,
      `---`,
      ``,
      narrative,
      ``,
      `---`,
      ``,
      `## Raw Transcript`,
      ``,
      `\`\`\``,
      transcript,
      `\`\`\``,
    ].join('\n');

    writeFileSync(outputPath, output, 'utf-8');
    console.log(`\nOutput written to: ${outputPath}`);

    return narrative;
  }
}
